using nsxtalbsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;
namespace nsxtalbsdk.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class NSXTALBHSMSafenetClientInfoType 
    {
        /// <summary>
        /// Generated File - Chrystoki.conf .
        /// </summary>
        [JsonProperty(PropertyName = "chrystoki_conf")]
        public string? ChrystokiConf { get; set; }
        /// <summary>
        /// Client Certificate generated by createCert.
        /// </summary>
        [JsonProperty(PropertyName = "client_cert")]
        public string? ClientCert { get; set; }
        /// <summary>
        /// Name prepended to client key and certificate filename.
        /// </summary>
        [JsonProperty(PropertyName = "client_ip")]
        [System.ComponentModel.DataAnnotations.Required]
        public string ClientIp { get; set; }
        /// <summary>
        /// Client Private Key generated by createCert.
        /// </summary>
        [JsonProperty(PropertyName = "client_priv_key")]
        public string? ClientPrivKey { get; set; }
        /// <summary>
        /// Major number of the sesseion.
        /// </summary>
        [JsonProperty(PropertyName = "session_major_number")]
        public int? SessionMajorNumber { get; set; }
        /// <summary>
        /// Minor number of the sesseion.
        /// </summary>
        [JsonProperty(PropertyName = "session_minor_number")]
        public int? SessionMinorNumber { get; set; }
    }
}
