using nsxtalbsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;
namespace nsxtalbsdk.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class NSXTALBWafLogType 
    {
        /// <summary>
        /// Set to true if there are allowlist rules in the policy. Field introduced in 20.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "allowlist_configured")]
        public bool? AllowlistConfigured { get; set; }
        /// <summary>
        /// Log Entries generated by WAF allowlist rules. Field introduced in 20.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "allowlist_logs")]
        public IList<NSXTALBWafAllowlistLogType> AllowlistLogs { get; set; }
        /// <summary>
        /// Set to true if allowlist rules were processed. Field introduced in 20.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "allowlist_processed")]
        public bool? AllowlistProcessed { get; set; }
        /// <summary>
        /// Log Entries generated by Application Specific Signature rules. Field introduced in 20.1.1.
        /// </summary>
        [JsonProperty(PropertyName = "application_rule_logs")]
        public IList<NSXTALBWafRuleLogType> ApplicationRuleLogs { get; set; }
        /// <summary>
        /// Set to true if there are Application Specific Signature rules in the policy. Field introduced in 20.1.1.
        /// </summary>
        [JsonProperty(PropertyName = "application_rules_configured")]
        public bool? ApplicationRulesConfigured { get; set; }
        /// <summary>
        /// Set to true if Application Specific Signature rules were executed. Field deprecated in 20.1.3. Field introduced in
        /// 20.1.1.
        /// </summary>
        [JsonProperty(PropertyName = "application_rules_executed")]
        public bool? ApplicationRulesExecuted { get; set; }
        /// <summary>
        /// Set to true if Application Specific Signature rules were processed. Field introduced in 20.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "application_rules_processed")]
        public bool? ApplicationRulesProcessed { get; set; }
        /// <summary>
        /// Latency (in microseconds) in WAF Request Body Phase. Field introduced in 17.2.2.
        /// </summary>
        [JsonProperty(PropertyName = "latency_request_body_phase")]
        public long? LatencyRequestBodyPhase { get; set; }
        /// <summary>
        /// Latency (in microseconds) in WAF Request Header Phase. Field introduced in 17.2.2.
        /// </summary>
        [JsonProperty(PropertyName = "latency_request_header_phase")]
        public long? LatencyRequestHeaderPhase { get; set; }
        /// <summary>
        /// Latency (in microseconds) in WAF Response Body Phase. Field introduced in 17.2.2.
        /// </summary>
        [JsonProperty(PropertyName = "latency_response_body_phase")]
        public long? LatencyResponseBodyPhase { get; set; }
        /// <summary>
        /// Latency (in microseconds) in WAF Response Header Phase. Field introduced in 17.2.2.
        /// </summary>
        [JsonProperty(PropertyName = "latency_response_header_phase")]
        public long? LatencyResponseHeaderPhase { get; set; }
        /// <summary>
        /// Set to true if there are Positive Security Model rules in the policy. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "psm_configured")]
        public bool? PsmConfigured { get; set; }
        /// <summary>
        /// Set to true if Positive Security Model rules were executed. Field deprecated in 20.1.3. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "psm_executed")]
        public bool? PsmExecuted { get; set; }
        /// <summary>
        /// Log Entries generated by WAF Positive Security Model. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "psm_logs")]
        public IList<NSXTALBWafPSMLogType> PsmLogs { get; set; }
        /// <summary>
        /// Set to true if Positive Security Model rules were processed. Field introduced in 20.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "psm_processed")]
        public bool? PsmProcessed { get; set; }
        /// <summary>
        /// Field introduced in 17.2.1.
        /// </summary>
        [JsonProperty(PropertyName = "rule_logs")]
        public IList<NSXTALBWafRuleLogType> RuleLogs { get; set; }
        /// <summary>
        /// Set to true if there are ModSecurity rules in the policy. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "rules_configured")]
        public bool? RulesConfigured { get; set; }
        /// <summary>
        /// Set to true if ModSecurity rules were executed. Field deprecated in 20.1.3. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "rules_executed")]
        public bool? RulesExecuted { get; set; }
        /// <summary>
        /// Set to true if ModSecurity rules were processed. Field introduced in 20.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "rules_processed")]
        public bool? RulesProcessed { get; set; }
        /// <summary>
        /// Denotes whether WAF is running in detection mode or enforcement mode, whether any rules matched the transaction, and
        /// whether transaction is dropped by the WAF module. Enum options - NO_WAF, FLAGGED, PASSED, REJECTED, WHITELISTED,
        /// BYPASSED. Field introduced in 17.2.2.
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string? Status { get; set; }
        /// <summary>
        /// Set to true if there are whitelist rules in the policy. Field deprecated in 20.1.3. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "whitelist_configured")]
        public bool? WhitelistConfigured { get; set; }
        /// <summary>
        /// Set to true if whitelist rules were executed. Field deprecated in 20.1.3. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "whitelist_executed")]
        public bool? WhitelistExecuted { get; set; }
        /// <summary>
        /// Log Entries generated by WAF whitelist rules. Field deprecated in 20.1.3. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "whitelist_logs")]
        public IList<NSXTALBWafWhitelistLogType> WhitelistLogs { get; set; }
    }
}
