using nsxtalbsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;
namespace nsxtalbsdk.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class NSXTALBWafPSMLogType 
    {
        /// <summary>
        /// Actions generated by this rule. Enum options - WAF_ACTION_NO_OP, WAF_ACTION_BLOCK, WAF_ACTION_ALLOW_PARAMETER. Field
        /// introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "actions")]
        public IList<string> Actions { get; set; }
        /// <summary>
        /// Name of the PSM group. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "group_name")]
        public string? GroupName { get; set; }
        /// <summary>
        /// UUID of the PSM group. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "group_uuid")]
        public string? GroupUuid { get; set; }
        /// <summary>
        /// Name of the PSM location. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string? Location { get; set; }
        /// <summary>
        /// Transaction data that matched the rule. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "matches")]
        public IList<NSXTALBWafRuleMatchDataType> Matches { get; set; }
        /// <summary>
        /// Rule ID of the matching rule. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "rule_id")]
        public string? RuleId { get; set; }
        /// <summary>
        /// Name of the matching rule. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "rule_name")]
        public string? RuleName { get; set; }
    }
}
