using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
namespace nsxtalbsdk.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class NSXTALBControllerAnalyticsPolicyType
    {
        /// <summary>
        /// Thresholds for various events generated by metrics system. Field introduced in 21.1.3.
        /// </summary>
        [JsonProperty(PropertyName = "metrics_event_thresholds")]
        public IList<NSXTALBMetricsEventThresholdType> MetricsEventThresholds { get; set; }
    }
}
