using nsxtalbsdk.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using NJsonSchema.Converters;
using System.ComponentModel;

namespace nsxtalbsdk.Models
{
    /// <summary>
    /// 
    /// </summary>
    public class NSXTALBWafWhitelistLogType 
    {
        public NSXTALBWafWhitelistLogType()
        {
        }
        /// <summary>
        /// Actions generated by this rule. Enum options - WAF_POLICY_WHITELIST_ACTION_ALLOW,
        /// WAF_POLICY_WHITELIST_ACTION_DETECTION_MODE, WAF_POLICY_WHITELIST_ACTION_CONTINUE. Field deprecated in 20.1.3. Field
        /// introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "actions")]
        public IList<string> Actions { get; set; }
        /// <summary>
        /// Name of the matched rule. Field deprecated in 20.1.3. Field introduced in 18.2.3.
        /// </summary>
        [JsonProperty(PropertyName = "rule_name")]
        public string? RuleName { get; set; }
    }
}
